

services:
  postgres:
    image: postgres:15
    container_name: loan_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: loan_db
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - loan_network

  redis:
    image: redis:7-alpine
    container_name: loan_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - loan_network

volumes:
  postgres_data:

networks:
  loan_network:
    driver: bridge